In [9]:
import numpy as np

In [5]:
data= [1,2,3,4,5]

In [6]:
np.array(data)

array([1, 2, 3, 4, 5])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [16]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [17]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [18]:
np.random.rand(3
            )

array([0.43489928, 0.11027206, 0.15813256])

In [19]:
np.random.rand(5,7)

array([[0.38839392, 0.13594093, 0.76161363, 0.95036116, 0.01014388,
        0.8877598 , 0.41124276],
       [0.19293026, 0.79628143, 0.75121458, 0.03085279, 0.59894561,
        0.33949263, 0.70522995],
       [0.01010307, 0.77100309, 0.64471264, 0.48290382, 0.74504375,
        0.81825019, 0.40919044],
       [0.2294488 , 0.59818263, 0.06463476, 0.4202265 , 0.43747608,
        0.65032937, 0.25851751],
       [0.77912772, 0.0369286 , 0.94380635, 0.23150367, 0.03327888,
        0.99905817, 0.8985489 ]])

In [20]:
np.random.randn(5,5)

array([[ 0.88806348, -0.03420794,  0.55524695,  0.08754522, -0.76042231],
       [ 1.56795112, -2.14191213,  0.10512135,  0.93975996, -0.63614043],
       [-0.33350443,  1.10105863,  1.94508034, -0.47371941,  0.03044937],
       [ 0.48447361, -0.72908795, -0.09702857, -0.35919194,  1.61004483],
       [-0.81999327, -0.76949801, -0.49129236,  0.62019421, -0.61020094]])

In [21]:
np.random.randint(1,50)

8

In [22]:
np.random.randint(1,50,10)

array([19, 15, 30, 12, 27, 19, 14, 34, 24, 24])

In [23]:
arr=np.arange(25)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
arr.max()

24

In [28]:
arr.min()

0

In [29]:
arr.argmax()

24

In [30]:
arr.argmin()

0

In [31]:
arr.sum()

300